#languages:
#  JavaScript: true

exclude_paths:
- ".gitignore"
- ".travis.yml"
- "LICENSE"
- "README.md"
- "Procfile"

engines:
  csslint:
    enabled: true
  coffeelint:
    enabled: true
  eslint:
    enabled: true

  duplication:
      enabled: true
      config:
        languages:
          - javascript

  nodesecurity:
    enabled: false
  fixme:
    enabled: false

ratings:
  paths:
    - "assets/**/*"
    - "public/**/*"
    - "**.js"
    - "**.coffee"
    - "**.styl"
    - "**.less"
    - "**.jade"
